# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dfe6daff74b4dfeff1d319318ab023e5024a00c933badb368ba6fdd50ae4dbd776136110c8e2d25d0295812a6fde2330d3540e75fa8f2d60dcff99af6a13c9f

test:
  secret_key_base: fd350ed8b6cf86ef8f727b719e8d3a2836e8b7cbe3a5b6240decd0d01b26d4d96cb849ff1dc70223a068aafb4ca8765a289c273933b69e36e1b5a44f13c84ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
